//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArizonaSignCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineItem
    {
        public int LineItem_ID { get; set; }
        public string description { get; set; }
        public decimal cost { get; set; }
        public int Invoice_ID { get; set; }
        public Nullable<decimal> taxPercent { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
