//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArizonaSignCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lift_Schedule
    {
        public System.DateTime Lift_Date { get; set; }
        public string Lift_Location { get; set; }
        public string Lift_Contact { get; set; }
        public string Customer_ID { get; set; }
        public int lift_Id { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
    
        public virtual Customer_Information Customer_Information { get; set; }
    }
}
