//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArizonaSignCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Contact_Method
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LU_Contact_Method()
        {
            this.Service_Request = new HashSet<Service_Request>();
        }
    
        public int Contact_ID { get; set; }
        public string Contact_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Request> Service_Request { get; set; }
    }
}
