//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArizonaSignCompany.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArizonaSignCompanyEntities : DbContext
    {
        public ArizonaSignCompanyEntities()
            : base("name=ArizonaSignCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LU_Contact_Method> LU_Contact_Method { get; set; }
        public virtual DbSet<Service_Request> Service_Request { get; set; }
        public virtual DbSet<Customer_Information> Customer_Information { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Lift_Schedule> Lift_Schedule { get; set; }
    }
}
