//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArizonaSignCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Request_number { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string Type { get; set; }
        public string description { get; set; }
        public byte[] attachment { get; set; }
        public string contact { get; set; }
        public string location { get; set; }
        public string company { get; set; }
    }
}
