//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArizonaSignCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Request
    {
        public Nullable<System.DateTime> Service_Date { get; set; }
        public string Service_Location { get; set; }
        public Nullable<System.TimeSpan> Service_Time { get; set; }
        public string Service_Contact { get; set; }
        public string Service_Issue { get; set; }
        public string Customer_ID { get; set; }
        public Nullable<int> Contact_ID { get; set; }
        public int Request_ID { get; set; }
    
        public virtual Customer_Information Customer_Information { get; set; }
        public virtual LU_Contact_Method LU_Contact_Method { get; set; }
    }
}
